### ISSUE TITLE
Chybejici prohlaseni prav majitele OpenStreetMap

### ISSUE THREAD

**Issue by Jakuje** [rh-lab-q/confla-android#9]
Aplikace ukazuje mapu, ale chybi spravny copyright

https://www.openstreetmap.org/copyright

![72973976_451995645667019_988092724349501440_n](https://user-images.githubusercontent.com/2694489/68069083-dfcb3a80-fd5b-11e9-952a-c4b12f4967c7.png)

**Comment by jmlich** [comment]
Mas pravdu a ja se omlouvam za spatne pouziti. Tady je to opravene:
76e0adb4cdb612d373c8ca909c1425a241be225d
Momentalne nemam nainstalovane vyvojove prostredi pro android, takze nevim kdy se to dostane skutecne do aplikace. Par dalsich patchu by pridalo dalsi duvod udelat nove apk (-;

**Comment by jmlich** [comment]
![image](https://user-images.githubusercontent.com/6171637/68071434-92aa9100-fd7a-11e9-8c1d-4c6d68a67604.png)

**Comment by jmlich** [comment]
fixed
